title: dogukaN
subtitle: Cyber Security and Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Cyber Security and Software Engineer

url: "https://dogukankurnaz.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: test.png
author: Dogukan Kurnaz
author_bio: I love cyber security and software engineering. I also enjoy writing scripts. I share the information I learned on my blog page, don't forget to follow. 
author_email: "dogukankurnaz@gmail.com"
author_location: Turkiye
author_website_url: "https://dogukankurnaz.github.io"
typewrite-text: Cyber Security and Software Engineer.... MSc in Software Engineering.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Innovance Consultancy
              company_logo: innovance.png
              #company_url: https://google.com
              designation: Cyber Security Engineer Intern
              description: Vulnerability Detection and Exploitation.

                          Preparation of handbooks on Ethnic Hacking.

                          Red Team membership and vulnerable server exploitation.
              visibility: true
            - company_name: Cekix Software
              company_logo: cekix1.png
              #company_url: https://microsoft.com
              designation: Penetration Tester
              description: Full-time penetration testing applications and closing of 3 vulnerabilities and necessary vulnerabilities in the website.
              visibility: true
            - company_name: Logical Defense
              company_logo: logdef.png
              #company_url: https://microsoft.com
              designation: Cyber Security Engineer Intern
              description: I tried training on NIDS systems, configuring setups.

                          I have worked on CentOS 7 and Ubuntu Server 18.04. I installed and tested software such as Snort, Suricata, PfSense.

                          I wrote local rules and to be tested.

                          I made cookbooks of these systems and processes.

                          I did exercises and about system administration.
              visibility: true

# Education
author_education_details:
              - college_logo: firat.png
                college_name: Firat University 
                college_url: https://www.firat.edu.tr/tr
                college_degree: Software Engineering
                description: Faculty of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: qrcode.png
                project_title: WiFi QR 
                project_description: Scan QR Code with camera and join WiFi connection
                project_url: https://github.com/dogukankurnaz/WifiQR
                visibility: true
              - project_thumbnail: xss.jpeg
                project_title: XSS Scanner
                project_description: When we scan the given domain with the CURL tool and print payload into it, if it is in it, it scans it again and adds it to the list.
                project_url: https://github.com/dogukankurnaz/XSS_Scanner
                visibility: true
              - project_thumbnail: subdomain.jpeg
                project_title: Subdomain Scanner
                project_description: Scans the site's subdomains. It makes OSINT work on existing site with database or long scan method.
                project_url: https://github.com/dogukankurnaz/subdomain_scanner
                visibility: true
              - project_thumbnail: backup.jpeg
                project_title: Linux Backup
                project_description: It backs up your files and saves it in /tmp.
                project_url: https://github.com/dogukankurnaz/LinuxBackup
                visibility: true
              - project_thumbnail: nft.png
                project_title: NFT Generator
                project_description: Generates random pixel avatar. You can use it in your NFT drawings.
                project_url: https://github.com/dogukankurnaz/nftgenerator
                visibility: true
              - project_thumbnail: ucak.png
                project_title: Military Aircraft Classification Project
                project_description: Prediction system with deep learning method using VGG16 Algorithm. Recognition of aircraft in military hangar by artificial intelligence method trained from data set. VGG16 algorithm MTARSI dataset was used.
                project_url: https://github.com/dogukankurnaz/military_aircraft_classification_project
                visibility: true
              - project_thumbnail: toplupenetrasyon.png
                project_title: Penetration Tool
                project_description: Combination of many ready-made tools in a single script.
                project_url: https://github.com/dogukankurnaz/TopluPenetrasyonAraci
                visibility: true
              - project_thumbnail: englishturkish.jpeg
                project_title: English-Turkish Words
                project_description: An app to learn Turkish and English vocabulary and test yourself
                project_url: https://github.com/dogukankurnaz/turkish-english
                visibility: true
              - project_thumbnail: password.png
                project_title: Password Generator
                project_description: 8-digit secure password creation program via Python
                project_url: https://github.com/dogukankurnaz/password-generator
                visibility: true
              - project_thumbnail: lfi.jpeg
                project_title: LFI Scanner
                project_description: Local File Inclusion control and reverse shell.
                project_url: https://github.com/dogukankurnaz/LFI_Scanner
                visibility: true

# social links
twitter_username: dogukankurnazz
github_username:  dogukankurnaz
linkedin_username: dogukankurnaz
instagram_username: dogukan_kurnaz
medium_username: dogukankurnaz
telegram_username: dgknkrnz

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

#disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: dogukankurnaz

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us8.list-manage.com/subscribe/post?u=f8215ba4abd9f20ecbe0875d2&amp;id=06455bab70&amp;f_id=006bc5e3f0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: mqkozggo

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
